// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Eu1wQgG5r1xo8BzsxoZUFEOaU2DxjMQ',
    appId: '1:1078897526340:web:663621a76e87240e9d9e11',
    messagingSenderId: '1078897526340',
    projectId: 'authenticator-flutter-940c9',
    authDomain: 'authenticator-flutter-940c9.firebaseapp.com',
    storageBucket: 'authenticator-flutter-940c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5opldJulQySMsmvn1_Qrxta_xWiLZDvo',
    appId: '1:1078897526340:android:fb86f6ff76581b279d9e11',
    messagingSenderId: '1078897526340',
    projectId: 'authenticator-flutter-940c9',
    storageBucket: 'authenticator-flutter-940c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVWwZ_IM1KOImfXsUL-2hDujfrs6oZK8',
    appId: '1:1078897526340:ios:9f81ea8bfa8102b19d9e11',
    messagingSenderId: '1078897526340',
    projectId: 'authenticator-flutter-940c9',
    storageBucket: 'authenticator-flutter-940c9.appspot.com',
    iosBundleId: 'com.example.authenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVWwZ_IM1KOImfXsUL-2hDujfrs6oZK8',
    appId: '1:1078897526340:ios:9f81ea8bfa8102b19d9e11',
    messagingSenderId: '1078897526340',
    projectId: 'authenticator-flutter-940c9',
    storageBucket: 'authenticator-flutter-940c9.appspot.com',
    iosBundleId: 'com.example.authenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Eu1wQgG5r1xo8BzsxoZUFEOaU2DxjMQ',
    appId: '1:1078897526340:web:b2517dd65da2fbb09d9e11',
    messagingSenderId: '1078897526340',
    projectId: 'authenticator-flutter-940c9',
    authDomain: 'authenticator-flutter-940c9.firebaseapp.com',
    storageBucket: 'authenticator-flutter-940c9.appspot.com',
  );
}
